export const authTypes = {
  /*signin*/
  FETCH_SIGNIN: 'FETCH_SIGNIN',
  SET_SIGNIN: 'SET_SIGNIN',
  SET_SIGNIN_LOADING: 'SET_SIGNIN_LOADING',
  SET_SIGNIN_ERROR: 'SET_SIGNIN_ERROR',

  /*signup*/
  FETCH_SIGNUP: 'FETCH_SIGNUP',
  SET_SIGNUP: 'SET_SIGNUP',
  SET_SIGNUP_LOADING: 'SET_SIGNUP_LOADING',
  SET_SIGNUP_ERROR: 'SET_SIGNUP_ERROR',

};