export const getDataActions = {
  SET_GET_DATA_LOADING: 'SET_GET_DATA_LOADING',
    GET_DATA: 'GET_DATA',
    SET_GET_DATA: 'SET_GET_DATA',
    SET_GET_DATA_ERROR: 'SET_GET_DATA_ERROR',
  };

  export const addDataActions = {
    SET_ADD_DATA_LOADING: 'SET_ADD_DATA_LOADING',
    ADD_DATA: 'ADD_DATA',
    SET_ADD_DATA: 'SET_ADD_DATA',
    SET_ADD_DATA_ERROR: 'SET_ADD_DATA_ERROR',
  };